version: "3.9"

services:
  server:
    build: ./server
    container_name: fastapi_server
    ports:
      - "8000:8000"

  client:
    build: ./client
    container_name: python_client
    depends_on:
      - server